export enum ProjectTypeEnums {
  STORYTIME_COMPANION = "STORYTIME_COMPANION",
  WANDERLUST_COMPANION = "WANDERLUST_COMPANION",
  WORDSMITH_COMPANION = "WORDSMITH_COMPANION",
}

export enum SummaryInputTypeEnum {
  TEXT = "Text",
  FILE = "File",
}
