export enum ProjectTypeEnums {
  GREETIFY_COMPANION = "GREETIFY_COMPANION",
  STORYTIME_COMPANION = "STORYTIME_COMPANION",
  WANDERLUST_COMPANION = "WANDERLUST_COMPANION",
  WORDSMITH_COMPANION = "WORDSMITH_COMPANION",
  COVER_LETTER_COMPANION = "COVER_LETTER_COMPANION",
}

export enum SummaryInputTypeEnum {
  TEXT = "Text",
  FILE = "File",
}
