import { z } from "zod";
import { createTRPCRouter, publicProcedure } from "@/server/api/trpc";
import { PromptTemplate } from "langchain/prompts";
import { StructuredOutputParser } from "langchain/output_parsers";
import summariseLLMQueryService from "@/services/api-service/sumarise-llm-query-service";
import commonApiService from "@/services/api-service/common-api-service";

// We can use zod to define a schema for the output using the `fromZodSchema` method of `StructuredOutputParser`.
const parser = StructuredOutputParser.fromZodSchema(
  z.object({
    coverLetter: z.string().describe("cover letter generated by the model"),
  })
);

const formatInstructions = parser.getFormatInstructions();

const prompt = new PromptTemplate({
  template: `

  You are an expert cover letter generator. You have a summarised resume and a summarised job description. You need to generate a cover letter that is {characterCount} characters long.

  ## Summarised Resume

  {resumeSummary}

  ## Summarised Job Description

  {jobDescriptionSummary}


  {format_instructions}
`,
  inputVariables: ["resumeSummary", "jobDescriptionSummary", "characterCount"],
  partialVariables: { format_instructions: formatInstructions },
});

export const coverLetter = createTRPCRouter({
  prompt: publicProcedure
    .input(
      z.object({
        resumeText: z.string(),
        jobDescription: z.string(),
        characterCount: z.number(),
      })
    )
    .mutation(async ({ input }) => {
      const { resumeText, jobDescription, characterCount } = input;

      const resumeSummaryParams = {
        textToSummarise: resumeText,
        characterCount: 1000,
      };
      const jobDescriptionSummaryParams = {
        textToSummarise: jobDescription,
        characterCount: 1000,
      };
      const resumeSummary = await summariseLLMQueryService.generateSummary(
        resumeSummaryParams
      );
      const jobDescriptionSummary =
        await summariseLLMQueryService.generateSummary(
          jobDescriptionSummaryParams
        );

      const model = commonApiService.generateModel();

      const inputParams = {
        resumeSummary: resumeSummary,
        jobDescriptionSummary: jobDescriptionSummary,
        characterCount: characterCount,
      };
      const llmInput = await commonApiService.generateFormattedLLMInput(
        prompt,
        inputParams
      );

      const llmResponse = await model.call(llmInput);

      const response = await parser.parse(llmResponse);

      const coverLetter = response.coverLetter;

      return { response: coverLetter };
    }),
});
